apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "my-website-chart.name" . }}
  name: {{ include "my-website-chart.name" . }}-svc
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "my-website-chart.name" . }}
  type: {{ .Values.service.type }}
